//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RollerTest.WebUI.Models.PROCEDURE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int PROCEDURE_FORCERCFG(Nullable<decimal> dELETEID)
        {
            var dELETEIDParameter = dELETEID.HasValue ?
                new ObjectParameter("DELETEID", dELETEID) :
                new ObjectParameter("DELETEID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROCEDURE_FORCERCFG", dELETEIDParameter);
        }
    
        public virtual int PROCEDURE_ROLLERBASESTATION(Nullable<decimal> dELETEID)
        {
            var dELETEIDParameter = dELETEID.HasValue ?
                new ObjectParameter("DELETEID", dELETEID) :
                new ObjectParameter("DELETEID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROCEDURE_ROLLERBASESTATION", dELETEIDParameter);
        }
    
        public virtual int PROCEDURE_ROLLERPROJECTINFO(Nullable<decimal> dELETEID)
        {
            var dELETEIDParameter = dELETEID.HasValue ?
                new ObjectParameter("DELETEID", dELETEID) :
                new ObjectParameter("DELETEID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROCEDURE_ROLLERPROJECTINFO", dELETEIDParameter);
        }
    
        public virtual int PROCEDURE_ROLLERRECORDINFO(Nullable<decimal> dELETEID)
        {
            var dELETEIDParameter = dELETEID.HasValue ?
                new ObjectParameter("DELETEID", dELETEID) :
                new ObjectParameter("DELETEID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROCEDURE_ROLLERRECORDINFO", dELETEIDParameter);
        }
    
        public virtual int PROCEDURE_ROLLERSAMPLEINFO(Nullable<decimal> dELETEID)
        {
            var dELETEIDParameter = dELETEID.HasValue ?
                new ObjectParameter("DELETEID", dELETEID) :
                new ObjectParameter("DELETEID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROCEDURE_ROLLERSAMPLEINFO", dELETEIDParameter);
        }
    
        public virtual int PROCEDURE_ROLLERTESTREPORTINFO(Nullable<decimal> dELETEID)
        {
            var dELETEIDParameter = dELETEID.HasValue ?
                new ObjectParameter("DELETEID", dELETEID) :
                new ObjectParameter("DELETEID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROCEDURE_ROLLERTESTREPORTINFO", dELETEIDParameter);
        }
    
        public virtual int PROCEDURE_TIMERCFG(Nullable<decimal> dELETEID)
        {
            var dELETEIDParameter = dELETEID.HasValue ?
                new ObjectParameter("DELETEID", dELETEID) :
                new ObjectParameter("DELETEID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROCEDURE_TIMERCFG", dELETEIDParameter);
        }
    }
}
